services:
  - type: web
    name: strava-dashboard
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: FRIEND_CLIENT_ID
        sync: false
      - key: FRIEND_CLIENT_SECRET
        sync: false
      - key: FRIEND_ACCESS_TOKEN
        sync: false
      - key: FRIEND_REFRESH_TOKEN
        sync: false
      - key: FRIEND_EXPIRES_AT
        sync: false
      - key: FRIEND_FIRSTNAME
        sync: false
      - key: FRIEND_LASTNAME
        sync: false
      - key: FRIEND_PHOTO
        sync: false
